### ISSUE TITLE
How to send JSON content.

### ISSUE THREAD

**Issue by godwdss** [Riigess/pallas#5]
I've installed it with PowerShell but I don't know how to send JSON content, can you tell me what the specific command is? What I need is com.apple.MobileAsset.Trial.Siri.SiriTextToSpeech for macOS15.

**Comment by Riigess** [comment]
The library doesn’t support two things you’re asking for here;
- Trial (used mostly pre-iOS 17.4/17.5 for Siri, as determine by your Asset identifier)
- And custom Assets

You will need to modify [Assets.py](https://github.com/Riigess/pallas/blob/main/src/pallas/utils/Assets.py) to add that asset, and then reinstall.

After that, you will be playing with Trial which behaves a little differently than UnifiedAssetFramework which is what I was focused on seeing as how it is currently in-use so this is untested behavior and untested overall.



Happy to add some more functionality in the library too, but it depends on his long you can wait. It might take me 3-4 weeks at least to add this functionality probably.. Hope the above helps though! :)

**Comment by godwdss** [comment]
> command

I can wait, please let me know the required command when the time comes, and if you don't want to make it public, email me godwdss@gmail.com.

**Comment by godwdss** [comment]
> The library doesn’t support two things you’re asking for here;
> 
> * Trial (used mostly pre-iOS 17.4/17.5 for Siri beyond TTS)
> * And custom Assets
> 
> You will need to modify [Assets.py](https://github.com/Riigess/pallas/blob/main/src/pallas/utils/Assets.py) to add that asset, and then reinstall.
> 
> After that, you will be playing with Trial which behaves a little differently than UnifiedAssetFramework which is what I was focused on seeing as how it is currently in-use for most assets so this is untested behavior and untested overall.
> 
> Happy to add some more functionality in the library too, but it depends on how long you can wait. It might take me 3-4 weeks at least to add this functionality probably.. Hope the above helps though! :)

I can wait, please let me know the required command when the time comes, and if you don't want to make it public, email me godwdss@gmail.com.

**Comment by Riigess** [comment]
Out of curiosity, what is your intent with TTS?

**Comment by godwdss** [comment]
> Out of curiosity, what is your intent with TTS?

Apple buys voices from Cerence, such as TTSAXResourceModelAssets, and the new Siri voice may also come from Cerence, and Cerence voice can be used on Android. That's why I want Siri voices.
By the way, There is no documentation on how to use Pallas. I don't know how to do.And i can't find the module docs for Python.

**Comment by Riigess** [comment]
No story built. As time is a valuable resource, closing Issue.

Feel free to re-open the issue if you can articulate the intent behind querying TTS or another asset.
